### ISSUE TITLE
Improve SketchAPI release process

### ISSUE THREAD

**Issue by nthState** [BohemianCoding/SketchAPI#513]
## Build output

Build output is an archive (*.zip or *.tar.gz) containing:

- Compiled/bundled SketchAPI JS file(s), shipped in `Sketch.app/Contents/Resources/SketchAPI*.js`
- Core modules (Node.js polyfills), shipped in `Sketch.app/Contents/Resources/core-modules/**`

As part of CI, on every commit the artefact is generated and published to a unique uri (service used here is an implementation detail, but S3 is a candidate).

### Example artefact uris

For a commit:

`https://{s3-bucket-uri}/{commit-hash}.zip`

For convenience the latest commit on a branch is available via a stable uri based on the branch name:

`https://{s3-bucket-uri}/{branch-name}.zip`

## Tests

Aside from linting, type-checking and other tests etc. integration tests should be run against Sketch itself during CI.

On developer workstations this is easy to achieve by downloading or building the desired Sketch version, while on CI we'll need the ability to use a specific version Sketch - especially when trying to coordinate updates to SketchAPI that also require changes to Sketch. A suggestion for how this could work on CI by using a branch naming convention:

- Look for a matching branch on the Sketch repo
    - If found, use the Sketch build from that branch for the integration tests
    - If not found, use the version from `develop`

## Integration with Sketch build process

The Sketch build process will be need to be updated roughly as follows:

- Remove SketchAPI as a submodule
- Add configuration that defines the SketchAPI build artefact uri to be included
- Download the artefact from the uri and extract to `Resources/`

### Updates to SketchAPI that don't affect Sketch

1. Open a PR in SketchAPI repo
2. Provide QA steps in PR description to validate work (maybe using `require('__pr')` or downloading the custom Sketch build from Jenkins)
3. Merge when QA and tests pass, and gather the resulting artefact url
4. Open PR on Sketch repo and update build config to point at a new SketchAPI asset url
5. Sketch is built on the PR against updated asset url

### Batching updates to Sketch repo

If working on many SketchAPI features in tandem it may be convenient to batch SketchAPI updates into a single PR on the Sketch repo to integrate

### Updates to SketchAPI that need to coordinate with Sketch updates

1. PR is opened on Sketch repo for necessary Sketch updates
2. PR is opened on SketchAPI repo, with mirrored branch naming, so the SketchAPI CI picks up the correct Sketch version
3. Work on PRs until the tests on the SketchAPI repo go green and pass QA, at this point, merge the SketchAPI PR and gather its artefact uri
4. Finally update the Sketch PR with the artefact uri, perform final QA and merge

## QA

We're proposing a QA step per pull request on SketchAPI

- Does it need separate Sketch builds for every commit? Is it too wasteful?
    - Can the Sketch build be cached? Ask Helen
    - Re-codesign after replacing the bundle `SketchAPI.js`
- Or, a way to inject dynamically SketchAPI artefact url into Sketch (not deterministic)

**Comment by nthState** [comment]
This issue is linked to issue: [https://github.com/BohemianCoding/Sketch/issues/17642](17642)

**Comment by nthState** [comment]
Here's a more concrete idea of what needs to happen

- New issue opened on SketchAPI
- Feature branch created: feature/123-new-method
- Developer fixes the issue commits to GitHub
- New SketchAPI Jenkins job starts
-- syncs SketchAPI repo
-- runs:
---- npm install
---- npm start
- This creates a subfolder called: build
- Create a new zip /branch-name/commit-hash.zip
-- Add the contents of build to the zip
-- Add core-modules/node_modules/*.* to core-modules to the zip

So you end up with a folder like:

SketchAPI_Async.js
SketchAPI_data-supplier.js
SketchAPI_dom.js
SketchAPI_settings.js
SketchAPI_ui.js
SketchAPI.js
coremodules/

This folder will exist as an artefact on Jenkins

- In the Sketch App, there would be a file: `sketchAPISource.manifest` It contains the URL to the SketchAPI.zip to use

```https://jm.sketchapp.com:9081/view/SketchAPI/archive/feature/123-new-method/hash.zip```

A pre-build script on the Sketch project would then download and extract the files to the correct locations, something like:

```FILE="sketchAPISource.manifest"
while IFS= read -r line
do
  curl -sS $line > file.zip && \
  unzip file.zip
done < "$input"```

**Comment by christianklotz** [comment]
Following is a recap of our discussion at the meet up this week, some of which overlaps with the original issue description above.

The code in the SketchAPI submodule source code is not used directly, meaning:

- updating the submodule doesn't actually update the bundled `SketchAPI.js`
- the build products of `npm build` is what gets bundled with the app
- removing the submodule and bundle the JavaScript API by downloading it from somewhere is less confusing

For the QA process we agreed that we limit Jenkins of Sketch with a bundled Javascript API to the Sketch repo only. Consequently, this pans out has follows for the two different scenarios.

### Updates to SketchAPI that don't affect Sketch
**Example:** Adding a new public API for an already existing internal API

1. Open PR on `SketchAPI`
1. CI (Jenkins instead of Circle?) builds the JavaScript API using `npm build`
1. Create a new zip `/<branch>/<commit-sha>.zip`
    - Add the contents of build to the ZIP file
    - Add `core-modules/node_modules/.` to core-modules to the ZIP file
1. Build artefact ends up on Jenkins `https://jm.sketchapp.com:9081/view/SketchAPI/archive/<branch>/SketchAPI-Modules-<commit-sha>.zip`
1. QA downloads ZIP file
1. QA opens Sketch either with command-line arg specifying bundle location or use _Debug_ menu item (TBC)

Sketch has a `default` called `SketchAPILocation` which allows to load `SketchAPI.js` from a [custom path](https://github.com/BohemianCoding/Sketch/blob/develop/Modules/SketchPluginManager/Source/MSPluginCommand.m#L92) but it doesn't seem to load the core modules from a custom path.

### Updates to SketchAPI that need to coordinate with Sketch updates (and release)
**Example:** Bug fix after internal Sketch API changed

1. Create new issue and branch on `Sketch`
1. Update the JavaScript bundle, TBC how exactly, e.g. a manifest file, part of a plist or different specifying the commit of `SketchAPI` matching the version of the ZIP that should be included in Sketch
1. Open PR on `Sketch`
1. Jenkins builds Sketch
    - Pull ZIP from server/linked Jenkins `SketchAPI` project
    - Unzip and copy its contents into `Resources`
    - Must only succeed on release builds, otherwise if no internet connection for local builds just skip similar to [existing strategy for `core-modules`](https://github.com/BohemianCoding/Sketch/blob/1ca8858c070dc999b988888f10dcbfab37e16d24/Modules/SketchPluginManager/Extras/Scripts/install-sketchAPI.sh)
1. QA downloads Sketch with correctly bundled API version


## To-do

- [ ] Make sure to the API _and_ core modules from a bundle, see [MSPluginCommand.m](https://github.com/BohemianCoding/Sketch/blob/develop/Modules/SketchPluginManager/Source/MSPluginCommand.m#L92-L115)
- [ ] Agree on whether _Debug_ menu item is required or command line is fine
- [ ] Pin SketchAPI to a specific version
- [ ] SketchAPI version setting in the Sketch repo and script to pull down build product
