### ISSUE TITLE
Add additional reference files

### ISSUE THREAD

**Issue by jedrichards** [BohemianCoding/SketchAPI#525]
As part of #515, flesh out the reference file section with addition types. Specifically:

- [x] Empty (Done in #516)
- [x] Shapes (#528)
- [x] Symbols (#528)
- [x] Foreign symbols and styles, e.g. Libraries (#532)
- [x] Symbol overrides (#536)
- [x] Fonts, text and typography (#536)
- [x] Groups (#537)
- [x] Images bitmap and vectors (#539)
- [x] Prototyping (#545 )
